### ISSUE TITLE
Move build ARG to runtime

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/device-bacnet-c#22]
Re: device-bacnet-c build automation 
The current way this build works doesn’t fit well with the standard build process we’re establishing with Jenkins Pipelines. As it stands the current build process would create separate images for the two different datalink types. We then would seemingly need both architecture types. This equates to 4 Docker images vs the standard 2 images. 

Can the build argument be a runtime argument instead?

**Comment by iain-anderson** [comment]
Suspect this won't be easy, as the datalink type is a build-time setting in the support library we use. Could we arrange for one docker image to contain both builds? ie both executables, both sets of sample configs, but everything else is common between the two builds anyway

**Comment by ernestojeda** [comment]
OK, that would be preferable. One image with both executables would work. The `entrypoint` could be a shell script that launches either of the two services based on either an env var or a runtime argument.

**Comment by iain-anderson** [comment]
Closed via #24
