### ISSUE TITLE
Upgrade to alpine 3.18

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/device-bacnet-c#76]
# 🚀 Feature Request

### Description [**REQUIRED**]
Upgrade to alpine 3.18

**Comment by bnevis-i** [comment]
Blocked on 404 for https://iotech.jfrog.io/artifactory/alpine-release/v3.18/main

**Comment by FelixTing** [comment]
fixed by https://github.com/edgexfoundry/device-bacnet-c/pull/87
