### ISSUE TITLE
Update Docker description for 3.0.1 patch release

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-bacnet-c#83]
# 📚 Docker Hub descriptions
### Description [**REQUIRED**]

 The following files need to be updated:
https://github.com/edgexfoundry/cd-management/blob/edgex-docker-hub-documentation/image-overview-templates/new-names/device-bacnet-arm64.md
https://github.com/edgexfoundry/cd-management/blob/edgex-docker-hub-documentation/image-overview-templates/new-names/device-bacnet.md

so that the 3.0.1 tag is listed here:
https://hub.docker.com/r/edgexfoundry/device-bacnet
https://hub.docker.com/r/edgexfoundry/device-bacnet-arm64

**Comment by FelixTing** [comment]
PR: https://github.com/edgexfoundry/cd-management/pull/368
